export const INIT_USER = 'INIT_USER';
export const GET_PERSONAL_USER = 'GET_PERSONAL_USER';
export const SET_PERSONAL_USER = 'SET_PERSONAL_USER';
export const UPDATE_PAYMENTS_FIELD_USER = 'UPDATE_PAYMENTS_FIELD_USER'
export const UPDATE_ADDRESS_FIELD_USER = 'UPDATE_ADDRESS_FIELD_USER'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const SHOW_MESSAGE = 'APP/SHOW_MESSAGE'
export const HIDE_MESSAGE = 'APP/HIDE_MESSAGE'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_BG_LOADER = 'APP/SHOW_BG_LOADER'
export const HIDE_BG_LOADER = 'APP/HIDE_BG_LOADER'

export const FETCH_ORDER = 'FETCH_ORDER'
export const ADD_TO_ORDER = 'ADD_TO_ORDER'
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER'
export const REMOVE_ORDER = 'REMOVE_ORDER'
export const MAKE_ORDER = 'MAKE_ORDER'
export const SET_ORDER = 'SET_ORDER'

export const FETCH_ADDRESS = 'FETCH_ADDRESS'
export const FETCH_TIME = 'FETCH_TIME'